service: jwt-authorizers
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    JWT_KEY: 'jtwexemplekey'

functions:
  authorizer:
    handler: src/auth.authorizer

  login:
    handler: src/auth.login
    events:
      - http:
          path: /login
          method: post
          cors: true      
  users-list:
    handler: src/users.list
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: authorizer
  users-create:
    handler: src/users.create 
    events:
      - http:
          path: users
          method: post
          cors: true 
          authorizer: authorizer

plugins:
  - serverless-offline

